import React, { useState } from 'react';
import { X, Download, Copy, Check, FileText, CheckCircle2 } from 'lucide-react';
import { GeoAuditReport } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: GeoAuditReport;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, report }) => {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'markdown' | 'json'>('markdown');

  if (!isOpen) return null;

  const generateMarkdown = () => {
    return `# Halls AI - Generative Engine Optimization (GEO) Audit Report
**Target Brand:** ${report.brand.name}
**Domain:** ${report.brand.domain || 'N/A'}
**Industry/Category:** ${report.brand.category}
**Generated on:** ${new Date().toLocaleDateString()}

---

## 1. Executive Summary
- **AI Visibility Score:** ${report.overview.visibilityScore} / 100
- **Share of Voice (SOV):** ${report.overview.shareOfVoice}%
- **AI Sentiment Score:** ${report.overview.sentimentScore}% Positive
- **Citation Frequency Rate:** ${report.overview.citationRate}%
- **Average Recommendation Rank:** #${report.overview.recommendationRankAvg.toFixed(1)}

---

## 2. Model Breakdown Matrix
${report.modelBreakdown
  .map(
    (m) =>
      `### ${m.model}
- **Mention Rate:** ${m.mentionRate}%
- **#1 Recommendation Rate:** ${m.firstRecommendationRate}%
- **Average Rank:** #${m.averageRank.toFixed(1)}
- **Citation Presence:** ${m.citationPresence}
- **Summary:** ${m.summarySnippet}`
  )
  .join('\n\n')}

---

## 3. High-Intent Prompt Performance
${report.topQueries
  .map(
    (q, i) =>
      `**Query ${i + 1}:** "${q.query}"
- **Rank:** #${q.brandRank}
- **Mentioned:** ${q.isMentioned ? 'Yes' : 'No'} | **Cited:** ${q.isCited ? 'Yes' : 'No'}
- **Snippet:** ${q.snippet}`
  )
  .join('\n\n')}

---

## 4. Key Citation & Knowledge Sources
${report.citationSources
  .map(
    (s) =>
      `- **${s.source}** (Authority: ${s.authorityScore}/100, Type: ${s.type})
  Influence: ${s.influence}`
  )
  .join('\n')}

---

## 5. Hallucination Alerts & Factual Safeguards
${
  report.hallucinationAlerts.length > 0
    ? report.hallucinationAlerts
        .map(
          (h) =>
            `- [${h.severity.toUpperCase()}] **${h.issue}**
  Discrepancy: ${h.detail}
  Targeted Resolution: ${h.suggestedFix}`
        )
        .join('\n')
    : 'No critical hallucinations detected.'
}

---

## 6. Actionable GEO Optimization Directives
${report.geoPlaybook
  .map(
    (p, i) =>
      `### ${i + 1}. ${p.title} [Priority: ${p.priority.toUpperCase()} | Impact: ${p.impact}]
${p.description}

\`\`\`
${p.actionableCode}
\`\`\``
  )
  .join('\n\n')}

---
*Report generated by ©Halls AI - Generative Engine Optimization Platform*
`;
  };

  const markdownContent = generateMarkdown();
  const jsonContent = JSON.stringify(report, null, 2);
  const activeContent = activeTab === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([activeContent], {
      type: activeTab === 'markdown' ? 'text/markdown' : 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `halls-ai-geo-report-${report.brand.name.toLowerCase()}.${
      activeTab === 'markdown' ? 'md' : 'json'
    }`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fadeIn">
      <div
        id="export-modal-container"
        className="w-full max-w-3xl rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl p-6 space-y-4 text-slate-100 max-h-[90vh] flex flex-col"
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-xl bg-indigo-600/20 text-indigo-400 border border-indigo-500/30">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-tight">
                Export GEO Intelligence Dossier
              </h3>
              <p className="text-xs text-slate-400">
                Full report for <strong className="text-slate-200">{report.brand.name}</strong>
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <div className="flex bg-slate-950 p-1 rounded-lg border border-slate-800 text-xs">
              <button
                onClick={() => setActiveTab('markdown')}
                className={`px-3 py-1 rounded-md font-medium transition-colors ${
                  activeTab === 'markdown' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                }`}
              >
                Markdown / Text
              </button>
              <button
                onClick={() => setActiveTab('json')}
                className={`px-3 py-1 rounded-md font-medium transition-colors ${
                  activeTab === 'json' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                }`}
              >
                Raw JSON
              </button>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="flex-1 overflow-y-auto rounded-xl bg-slate-950 border border-slate-800/90 p-4 font-mono text-xs text-slate-300 leading-relaxed whitespace-pre-wrap select-all">
          {activeContent}
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-800">
          <span className="text-xs text-slate-500">
            Export ready for executive review or engineering sprint planning.
          </span>
          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 flex items-center space-x-1.5 transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  <span>Copy to Clipboard</span>
                </>
              )}
            </button>
            <button
              onClick={handleDownload}
              className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-xs font-semibold text-white flex items-center space-x-1.5 transition-colors shadow-sm"
            >
              <Download className="w-4 h-4" />
              <span>Download File</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
