import React from 'react';
import { ShieldAlert, AlertTriangle, CheckCircle, Wrench, ArrowRight } from 'lucide-react';
import { HallucinationAlert } from '../types';

interface HallucinationDefenseProps {
  alerts: HallucinationAlert[];
  brandName: string;
}

export const HallucinationDefense: React.FC<HallucinationDefenseProps> = ({ alerts, brandName }) => {
  const getSeverityBadge = (sev: string) => {
    switch (sev.toLowerCase()) {
      case 'high':
        return 'bg-rose-500/10 text-rose-400 border-rose-500/30';
      case 'medium':
        return 'bg-amber-500/10 text-amber-400 border-amber-500/30';
      default:
        return 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30';
    }
  };

  return (
    <div id="hallucination-defense-section" className="p-5 rounded-2xl bg-slate-900/60 border border-slate-800 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800/80 pb-3">
        <div>
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-amber-400" />
            <span>AI Hallucination & Accuracy Defense</span>
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Detect and correct factual errors, outdated specs, and inaccurate claims generated by LLMs about{' '}
            <strong className="text-slate-200">{brandName}</strong>
          </p>
        </div>
      </div>

      {/* Alerts list */}
      <div className="space-y-3">
        {alerts.length === 0 ? (
          <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 text-emerald-300 text-xs flex items-center space-x-2">
            <CheckCircle className="w-4 h-4 text-emerald-400" />
            <span>No critical AI hallucinations detected for {brandName}. All facts verified accurate across tested engines.</span>
          </div>
        ) : (
          alerts.map((alert, idx) => (
            <div
              key={idx}
              className="p-4 rounded-xl bg-slate-950/80 border border-slate-800/90 hover:border-slate-700 transition-colors space-y-2.5"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <AlertTriangle className="w-4 h-4 text-amber-400" />
                  <span className="text-xs font-bold text-white tracking-tight">{alert.issue}</span>
                </div>
                <span
                  className={`px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider border ${getSeverityBadge(
                    alert.severity
                  )}`}
                >
                  {alert.severity} Risk
                </span>
              </div>

              {/* Detail */}
              <p className="text-xs text-slate-300 leading-relaxed bg-slate-900/40 p-2.5 rounded border border-slate-800/60">
                <span className="text-slate-400 font-semibold">Detected Inaccuracy: </span>
                {alert.detail}
              </p>

              {/* Suggested Fix */}
              <div className="flex items-start space-x-2 text-xs text-indigo-300 pt-1">
                <Wrench className="w-3.5 h-3.5 text-indigo-400 mt-0.5 flex-shrink-0" />
                <div className="space-y-0.5">
                  <span className="font-semibold text-slate-300">Targeted Resolution: </span>
                  <span className="text-slate-300">{alert.suggestedFix}</span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
